######## Application Access Point ########

server:
  address: localhost
  port: 8080
  #contextPath: /

#management:
  #port: 8081
  #contextPath: /manage


######## Database Access Point ########

spring.datasource:
    url: jdbc:mysql://sntesting.cxx3do2mvbqb.us-east-1.rds.amazonaws.com:3306/sntesting
    username: sntesting
    password: sntesting
    driverClassName: com.mysql.jdbc.Driver